#
# Copyright 2020-2023 Enflame. All Rights Reserved.
#
import os
import torch_gcu
import logging
from functools import partial
from contextlib import contextmanager
from typing import Callable, Optional

__all__ = [
    "OpDebugCtx",
    "get_pre_func",
    "get_post_func",
    "get_op_statistics_info",
    "compile_trace_start",
    "compile_trace_end",
    "user_trace_point",
    "set_logging_level",
    "tops_host_trace_start",
    "tops_host_trace_end",
    "tops_host_trace_range",
    "tops_host_trace_point",
]


def user_trace_point(trace_info: str = ''):
    """Add user_trace_point at host and dummy_kernels at device for debug.

    Args:
      trace_info: kernel meta info for debug.
    """
    return torch_gcu._C._user_trace_point(trace_info)


def compile_trace_start(name: str = "", payload: str = ""):
    """ Start a compile trace point for debug.
        You can see it in profile data generated by Tops profiler tool

    Args:
        name: trace point name show in profile data.
    """
    return torch_gcu._C._compile_trace_start(name, payload)


def compile_trace_end(name: str = ""):
    """ End a compile trace point for debug, which is started by compile_trace_start.

    Args:
        name: trace point name show in profile data.
    """
    return torch_gcu._C._compile_trace_end(name)

def tops_host_trace_start(name: str = "", payload: str = ""):
    """ Start a host trace point in vpd for debug.
        You can see it in profile data generated by Tops profiler tool
    """
    return torch_gcu._C._user_trace_start(name, payload)

def tops_host_trace_end(name: str = ""):
    """ End a host trace point in vpd for debug, which is started by tops_host_trace_start.
    """
    return torch_gcu._C._user_trace_end(name)

@contextmanager
def tops_host_trace_range(name: str, payload: str = ""):
    tops_host_trace_start(name, payload)
    yield
    tops_host_trace_end(name)

def tops_host_trace_point(name: str = '', payload: str = ""):
    return torch_gcu._C._tops_host_trace_point(name, payload)

class OpDebugCtx(object):

    def __init__(self,
                 enable_dump_op_name: bool = True,
                 enable_fallback_cpu: bool = False,
                 enable_op_check: bool = False):
        self.enable_dump_op_name = enable_dump_op_name
        self.enable_fallback_cpu = enable_fallback_cpu
        self.enable_op_check = enable_op_check

    def __enter__(self):
        print(
            f"[OpDebugCtx] Enter OpDebugCtx with config: enable_fallback_cpu={self.enable_fallback_cpu}"
        )
        self.enable_scope()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.disable_scope()

        print("[OpDebugCtx] Exit OpDebugCtx")

    # Used in torch node hook to control op behavior in autograd
    def enable_scope(self, _=None):
        if self.enable_dump_op_name:
            torch_gcu._C._enter_dump_op_name_scope()
        if self.enable_fallback_cpu:
            torch_gcu._C._enter_fallback_cpu_scope()
        if self.enable_op_check:
            torch_gcu._C._enter_op_check_scope()

    def disable_scope(self, _=None, __=None):
        torch_gcu._C._exit_print_cpp_name_scope()
        torch_gcu._C._exit_fallback_cpu_scope()
        torch_gcu._C._exit_op_check_scope()

    @staticmethod
    def print_current_state():
        print(
            f"[OpDebugCtx] enter_dump_op_name_scope: {torch_gcu._C._get_dump_op_name_scope_state()}"
        )
        print(
            f"[OpDebugCtx] enter_fallback_cpu_scope: {torch_gcu._C._get_fallback_cpu_scope_state()}"
        )
        print(
            f"[OpDebugCtx] enter_op_check_scope: {torch_gcu._C._get_op_check_scope_state()}"
        )


def get_pre_func(h: Optional[OpDebugCtx] = None) -> Callable:
    if h is None:
        h = OpDebugCtx()
    return partial(h.enable_scope, h)


def get_post_func(h: Optional[OpDebugCtx] = None) -> Callable:
    if h is None:
        h = OpDebugCtx()
    return partial(h.disable_scope, h)


def get_op_statistics_info() -> str:
    """Retrieves a string containing the op statistics info."""
    return torch_gcu._C._get_op_statistics_info()

def dump_op_statistics_info():
    """Dump the op statistics info to json file"""
    torch_gcu._C._dump_op_statistics_to_json()

def clear_op_statistics_info():
    """Clear the op statistics info"""
    torch_gcu._C._clear_statistics()


def set_logging_level(level, file_name: str = None):
    """Set the logging level of the op statistics info

    Args:
        level (int): The logging level to set. Default: 1, means DEBUG level
        logging.NOTSET,
        logging.DEBUG,
        logging.INFO,
        logging.WARN,
        logging.ERROR,
        logging.FATAL,
    """
    if level not in [
        logging.NOTSET,
        logging.DEBUG,
        logging.INFO,
        logging.WARN,
        logging.ERROR,
        logging.FATAL,
    ]:
        raise ValueError(
            f"Invalid logging level: {level}, must be in [logging.NOTSET, logging.DEBUG, logging.INFO, logging.WARN,logging.ERROR, logging.FATAL]"
        )

    # reset logging
    log = logging.getLogger()
    for hd in log.handlers[:]:
        log.removeHandler(hd)

    # set logging level
    if file_name != None:
        import os
        local_rank = int(os.environ["LOCAL_RANK"])
        file_name = file_name +"-rank_"+ str(local_rank) + ".log"

        logging.basicConfig(filename=file_name, level=level, format='%(asctime)s %(levelname)s: %(message)s')
    else:

        logging.basicConfig(level=level, format='%(asctime)s %(levelname)s: %(message)s')


class AllowINT64AndUINT64Ctx(object):
    """Context manager to allow INT64 and UINT64 when supported by backend."""

    def __enter__(self):
        os.environ["TORCH_GCU_ENABLE_INT64_AND_UINT64"] = "true"

    def __exit__(self, exc_type, exc_val, exc_tb):
        os.environ["TORCH_GCU_ENABLE_INT64_AND_UINT64"] = "false"
