###############################################################
#
# Copyright 2020 The Enflame Tech Company. All Rights Reserved.
#
# Brief:
#   Build Installation documents
#
###############################################################

include doc.mk

