/*
 * Copyright 2023-2024 Enflame. All Rights Reserved.
 */

#include <ATen/TensorIterator.h>

#include "aten/aot_ops/gcu_empty_tensor.h"
#include "aten/aot_ops/gcu_resize.h"
#include "aten/shape_inference/shape_infer_func.h"

namespace torch_gcu {

namespace aotops {

at::Tensor& binary_cross_entropy_out_shape_infer(
    const at::Tensor& input, const at::Tensor& target,
    const c10::optional<at::Tensor>& weight_opt, int64_t reduction,
    at::Tensor& loss) {
  // resize
  if (reduction == at::Reduction::None) {
    aotops::resize_output(loss, input.sizes());
  } else {
    aotops::resize_output(loss, {});
  }
  // check
  at::TensorIteratorConfig()
      .resize_outputs(false)
      .declare_static_shape(loss.sizes())
      .add_output(loss)
      .add_owned_input(input)
      .add_owned_input(target)
      .build();
  return loss;
}

at::Tensor binary_cross_entropy_shape_infer(
    const at::Tensor& input, const at::Tensor& target,
    const c10::optional<at::Tensor>& weight_opt, int64_t reduction) {
  auto out = aotops::empty({0}, input.options());
  binary_cross_entropy_out_shape_infer(input, target, weight_opt, reduction,
                                       out);
  return out;
}

at::Tensor& huber_loss_out_shape_infer(const at::Tensor& self,
                                       const at::Tensor& target,
                                       int64_t reduction, double delta,
                                       at::Tensor& result) {
  TORCH_CHECK(delta > 0,
              "huber_loss does not support non-positive values for delta.")
  if (reduction == at::Reduction::None) {
    auto iter = at::TensorIterator::borrowing_binary_op(result, self, target);
  } else {
    result.resize_({});
  }
  return result;
}

at::Tensor huber_loss_shape_infer(const at::Tensor& self,
                                  const at::Tensor& target, int64_t reduction,
                                  double delta) {
  TORCH_CHECK(delta > 0,
              "huber_loss does not support non-positive values for delta.")
  at::Tensor loss;
  if (reduction == at::Reduction::None) {
    loss = at::empty_like(self);
    auto iter = at::TensorIterator::borrowing_binary_op(loss, self, target);
  } else {
    loss = at::empty({}, self.options());
  }

  return loss;
}

// mse_loss_shape_infer and mse_loss_out_shape_infer are generated by codegen
// in structured_shape_infer_func.cpp, so we don't need to implement them here.

at::Tensor& mse_loss_backward_out_shape_infer(const at::Tensor& grad_output,
                                              const at::Tensor& self,
                                              const at::Tensor& target,
                                              int64_t reduction,
                                              at::Tensor& grad_input) {
  // grad_input has the same shape as self, since it's the gradient of self
  aotops::resize_output(grad_input, self.sizes());
  // Use TensorIteratorConfig to validate shape compatibility (including
  // grad_output broadcasting) TensorIterator will automatically handle scalar
  // grad_output broadcasting
  at::TensorIteratorConfig()
      .resize_outputs(false)
      .declare_static_shape(grad_input.sizes())
      .add_output(grad_input)
      .add_const_input(self)
      .add_const_input(target)
      .add_const_input(grad_output)
      .build();
  return grad_input;
}

at::Tensor mse_loss_backward_shape_infer(const at::Tensor& grad_output,
                                         const at::Tensor& self,
                                         const at::Tensor& target,
                                         int64_t reduction) {
  // Create output tensor with the same shape as self (matching PyTorch's
  // zeros_like)
  auto grad_input = aotops::empty(self.sizes(), self.options());
  // Call out version to maintain nesting relationship (matching PyTorch
  // implementation)
  mse_loss_backward_out_shape_infer(grad_output, self, target, reduction,
                                    grad_input);
  return grad_input;
}

}  // namespace aotops

}  // namespace torch_gcu
