# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
# sys.path.insert(0, os.path.abspath('./'))

doc_root = os.getenv('DOC_ROOT', "INVALID")
pkg_ver = os.getenv('EFB_PKG_VER', 'master')
pkg_ver = pkg_ver if pkg_ver.strip() else 'master'

# -- Project information -----------------------------------------------------

project = 'torch_gcu2.9算子支持列表'
copyright = 'Copyright 2025 Enflame. All Rights Reserved.'
author = 'www.enflame-tech.com'

# The full version, including alpha/beta/rc tags
release = 'V3.7.1' # 填写当前文档版本号
doc_name = 'Torch-GCU2.9算子支持列表' # 填写全称
last_update_date = '2026年3月16日' # 填写文档更新日期，格式为YYYY年M月D日
pdf_filename = 'Torch-GCU2.9算子支持列表.tex' # 填写导出的pdf的tex文件名，格式为"XXXX.tex"，注意不可以含有空格！！！

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

extensions = [
#  'sphinx.ext.autodoc',
#  'sphinx_markdown_tables',
#  'recommonmark',
]

#source_suffix = {
#    '.rst': 'restructuredtext',
#    '.txt': 'markdown',
#     '.md': 'markdown',
#}

#source_parsers = {
#   '.md': 'recommonmark.parser.CommonMarkParser',
#}

if doc_root != "INVALID":
  #extensions.append('autoapi.extension')
  #autoapi_type = 'python'
  #autoapi_dirs = [doc_root + '/tool/efml/bindings/python']
  autoapi_ignore = ['*test*', '*example*', '*setup*', '*pyefml_int.py*', '*autoapi*']  #skip internal test code
  #autoapi_root = '_build/api/efml'
  autoapi_generate_api_docs = True #True

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["sphinx_multiversion"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build']

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_title = doc_name
html_theme = 'sphinx_rtd_theme'# sphinx_rtd_theme
html_short_title = '在线文档中心'
html_logo = './_static/enflame_logo.png'
html_sidebars = {
    "**": [
        "versions.html",
        ],
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

#################################################
# 以下为lilian添加的
#################################################
# 数字，表格，代码块如果有标题，是否会自动编号。true：编号；false：不编号
numfig = True
# 定义html页面图表编号格式
numfig_format = {
    'figure':'图%s ',
    'table':'表%s ',
}
# 设置图表编号的层级
numfig_secnum_depth = 1

master_doc = 'index'

# -- Options for LaTeX output ---------------------------------------------
# 注意第二个参数不能包含空格，否则报错
latex_documents = [
    (master_doc,pdf_filename,'',author,'manual',True),
]

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '10pt, oneside',

    # Additional stuff for the LaTeX preamble.
    #
    'preamble': r'''
\usepackage{pdfpages}
\usepackage{graphicx}

% 设置图表名称格式
\usepackage{caption}
\DeclareCaptionFormat{mytablecaption}{\raggedright \small{#1 #3}} %9号字体大小，编号与文字之间只有一个空格，靠左显示
\DeclareCaptionFormat{myfigurecaption}{\small{#1 #3}} %9号字体大小，编号与文字之间只有一个空格，居中显示
\captionsetup{format=mytablecaption} %不知道为什么[table]不好使，但这样也实现了
\captionsetup[figure]{format=myfigurecaption}

% 引入设置表头背景色所需要的宏包
\usepackage{color}
\usepackage{colortbl}

% 设置中英文字体
\usepackage[UTF8,heading=true]{ctex}
\usepackage{xeCJK}
\xeCJKsetup{AutoFakeSlant={true},AutoFakeBold={true}}
\setCJKmainfont{SimSun}
\setCJKmonofont{SimSun}
\setmainfont{Calibri}

% 设置页边距
\usepackage{geometry}
\geometry{left=3.17cm,right=3.17cm,top=2.08cm,bottom=2.54cm}

% 设置页眉页脚位置
\setlength{\topmargin}{-1.04cm} %页边距顶端到header顶端的距离
\setlength{\footskip}{0.6cm} %页边距底端到footer底端的距离
\setlength{\headheight}{0.56cm} %header的高度
\setlength{\headsep}{0.1cm} %header底端到正文的距离
% 设置页眉页脚样式
\usepackage{lastpage}
\fancypagestyle{titleheadstyle}{
    \fancyhf{}
    \fancyhead[EOLH]{}
    \fancyhead[EORH]{}
    \fancyfoot[EOCF]{}
    \fancyfoot[EORF]{}
    \renewcommand{\headrulewidth}{0.75pt}
    \renewcommand{\footrulewidth}{0pt}
}
\fancypagestyle{normal}{
    \fancyhf{}
    \fancyhead[EOLH]{\zihao{6} ''' + doc_name + r'''}
    \fancyhead[EORH]{\zihao{6} \leftmark}%leftmark,rightmark
    \fancyfoot[EOCF]{\zihao{-6} 版权所有©2025-2026 上海燧原科技股份有限公司保留所有权利}
    \fancyfoot[EORF]{\zihao{-6} \thepage\ / \ \pageref{LastPage}}
    \renewcommand{\headrulewidth}{0.75pt}
    \renewcommand{\footrulewidth}{0pt}
}
\fancypagestyle{plain}{
    \fancyhf{}
    \fancyhead[EOLH]{\zihao{6} ''' + doc_name + r'''}
    \fancyhead[EORH]{\zihao{6} \leftmark}%leftmark,rightmark
    \fancyfoot[EOCF]{\zihao{-6} 版权所有©2025-2026 上海燧原科技股份有限公司保留所有权利}
    \fancyfoot[EORF]{\zihao{-6} \thepage\ / \ \pageref{LastPage}}
    \renewcommand{\headrulewidth}{0.75pt}
    \renewcommand{\footrulewidth}{0pt}
}

% 设置水印
% 定义水印颜色（#C0C0C0）
%\usepackage{color}
\definecolor{watermarkcolor}{RGB}{192,192,192}
\usepackage[
    contents = Enflame-Tech.\ All\ rights\ reserved.,
    color = watermarkcolor,
    scale = 6,
    opacity = 0.3,
]{background}

% 设置目录格式
\usepackage{titletoc}
%\titlecontents{标题名}[左间距]{标题格式可空置}{标题标志}{无序号标题可空置}{指引线与页码}[下间距]
\titlecontents{chapter}[1.8em]{\zihao{-4} \color{black}}{\contentslabel{1.5em}}{}{\titlerule*[0.6pc]{.}\contentspage}[\addvspace{0pt}]

%（未采用该方法）一级标题有固定的背景
%\usepackage{wallpaper}
%\ThisULCornerWallPaper{0.8}{level1.png}

% 设置各级标题样式
% 定义二级以上标题颜色（#A9423B）
\usepackage{color}
\definecolor{headingcolor}{RGB}{169,66,59}
% 定义一级标题的背景（levle1.png）
\usepackage{eso-pic}
\newcommand{\BackgroundPic}{
    \put(88,710){
        \parbox[b]{\textwidth}{
            %\vfill
            \centering
            \includegraphics[width=\textwidth,keepaspectratio]{level1.png}
            %\vfill
        }
    }
}
% 设置各级标题样式（颜色、大小、间距等）
\ctexset{
    chapter = {
        name = {},%第，章
        number = \arabic{chapter},
        format = \bfseries\color{white}\zihao{-1}\AddToShipoutPictureBG*{\BackgroundPic},
        beforeskip = -6pt, %标题前的垂直距离
        afterskip = 25pt, %标题后的垂直距离
        indent = 0pt, %首行缩进
    },
    section = {
        format = \color{headingcolor}\huge,%\zihao{-2}，-2是18，2是22，huge是21。。。。。。
        beforeskip = 0pt,
        afterskip = 0pt,
        indent = 0pt,
    },
    subsection = {
        format = \color{headingcolor}\zihao{3},
        beforeskip = 0pt,
        afterskip = 0pt,
        indent = 0pt,
    },
    subsubsection = {
        format = \color{headingcolor}\zihao{-4},
        beforeskip = 0pt,
        afterskip = 0pt,
        indent = 0pt,
    }
}

% 设置链接的颜色
\definecolor{myurlcolor}{RGB}{68,114,196}
\hypersetup{
    colorlinks = true,
    linkcolor = black, %所有内部链接的颜色设置为黑色（目录、页码等）
    urlcolor = myurlcolor, %URL的颜色设置为自定义蓝色（正文中的URL）
}

% 设置首行缩进，em为一个字的宽度，0em即不缩进，2em为缩进两个字的宽度
\usepackage{indentfirst}
\setlength{\parindent}{2em}
''',

    # Latex figure (float) alignment
    #
    'figure_align': 'H',

    #Override if you want to generate a differently styled title page.
    #'maketitle': '\includepdf{titleTex.pdf}',
    'maketitle': r'''
\thispagestyle{titleheadstyle}

%此处为文档Logo，请勿随意修改
\centerline{\includegraphics[width=5.76in]{enflame_logo.png}}
~\\
~\\
~\\
~\\
\centerline{\zihao{1} ''' + doc_name + r'''} %此处为文档名称
~\\
~\\
~\\
~\\
\centerline{\zihao{1} ''' + release + r'''} %此处为文档版本
~\\
~\\
~\\
~\\
~\\
~\\
~\\
~\\
~\\
~\\
\centerline{\zihao{3} ''' + last_update_date + r'''} %此处为文档更新时间

''',
}

latex_logo = './_static/enflame_logo.png'

latex_additional_files = [
    './_static/level1.png'
]

latex_engine = 'xelatex' # 默认为pdflatex
